auto:           false
server:         false
server_port:    4000
baseurl:        /
url:            http://localhost:4000
exclude:        readme.md, config.rb, .sass-cache, start.sh, compile.sh, watch.sh